docker_image_name: my-website
dockerfile_src_path: /Users/ahaughton/Documents/Projects/ansible/playbooks/docker/dockerfile
dockerfile_dest_path: /home/ansible/dockerfile
dockerfile_build_path: /home/ansible/
owner: ansible
container_port_mapping: "80:80"
package_name: docker
