---

- name: Create EC2 instance
  amazon.aws.ec2_instance:
    region: "{{ region }}"
    name: "docker_web_server"
    image_id: "{{ image_id }}"
    instance_type: "{{ instance_type }}"
    key_name: "{{ key_name }}"
    security_groups: "{{ security_groups }}"
    count: 1
    wait: yes
    subnet_id: "{{ subnet_id }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    filters:
      instance-state-name: running
      "tag:Name": "docker_site"
  register: ec2_result

- name: Add new instance to inventory
  ansible.builtin.add_host:
    name: "{{ ec2_result.instances[0].public_ip_address }}"
    ansible_host: "{{ ec2_result.instances[0].public_ip_address }}"
    ansible_user: ec2-user
    ansible_ssh_private_key_file: "{{ private_key_path }}"
    groups: dynamic_vm
  
- name: Set Fact for VM IP
  ansible.builtin.set_fact:
    docker_target_ip: "{{ ec2_result.instances[0].public_ip_address }}"

- name: Copy SSH key to Node
  ansible.builtin.copy:
    src: /Users/ahaughton/Downloads/docker_key.pem
    dest: /home/ec2-user/
    mode: 400