- name: Copy Dockerfile to EC2 instance
  copy:
    src: "{{ dockerfile_src_path }}"
    dest: "{{ dockerfile_dest_path }}"
    owner: "{{ file_owner }}"
    group: "{{ file_owner }}"
    mode: "{{ file_mode }}"
