---

- name: Create Docker Image and Deploy
  hosts: docker
  become: true
  roles:

    - role: update_repos
      tags:
        - update_repos
      # Update the packages on the host
      
    - role: install_docker
      tags:
        - install_docker
      # Install Docker and Start the Service

    - role: copy_dockerfile
      tags: 
        - copy_dockerfile
      # Ensure that the Dockerfile is copied before building the image

    - role: build_docker_image
      tags:
        - build_docker_image
      # Build Docker Image

    - role: run_docker_container
      tags:
        - run_docker_container
      # Run the container
